Add all errors from GnuTLS, Botan and mbedTLS
crocs-muni/usable-cert-validation pull request #85
Opened 2020-08-21 17:01 UTC by valcikeric

I've created separate files for all errors from the above-mentioned libraries.
I was following [this file](https://docs.google.com/spreadsheets/d/1BTnOt-9_wFopiiUsifMjxxJZbo3bId1qqN4HAos_zU0/edit?usp=sharing).

The only thing that should be done (I was thinking I'd include it in this PR, but I wasn't sure) is the tags in each error. In other words, the categories. Right now, every new error has category `uncategorized`.

I think I'm able to add those categories by myself, but it would take some more time. Should I add them next? I can make this PR work in progress and add them a little later, but if you are OK with having all the codes uncategorized for now, this PR is ready to be reviewed.

2020-08-24 15:10 UTC, mukrop commented
Having no categories is OK for now, I'll review the PR soon (probably tomorrow). And I agree that trying to assign some (or trying to map on the existing in OpenSSL) is a good next step.

2020-08-24 19:23 UTC, mukrop requested changes
Seems nice. Only two comments:
* Investigating a suspicious case, I stumbled upon Botan's OSCP_NO_REVOCATION_URL and OSCP_SERVER_NOT_AVAILABLE codes that are [deprecated due to a typo](https://botan.randombit.net/doxygen/cert__status_8h_source.html) (OSCP instead of OCSP). Can you add the corresponding deprecation message as for OpenSSL?
* As per [Botan source files](https://botan.randombit.net/doxygen/cert__status_8h_source.html), the `OK` and `VERIFIED` codes are synonymous. That's wy we don't list the `OK` code in the overview table. Can you please delete `OK`? (I favous `VERIFIED` since [Botan sources](https://botan.randombit.net/doxygen/cert__status_8cpp_source.html) use it.)

2020-08-30 14:15 UTC, valcikeric commented
I've done the changes you asked for, the PR should be ready to merge now. :-)

2020-09-02 15:56 UTC, mukrop approved these changes

2020-09-02 15:56 UTC, merged